# Site settings
title: Chau's Website
email: hello@chau-nguyen.de
description: > # this means to ignore newlines until "baseurl:"
  Huyen Chau Nguyen is a computer science student at Kalsruher Institute of Technology. On this website you can find out more about her.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chau-nguyen.de" # the base hostname & protocol for your site
twitter_username: c64au
github_username:  chaupow

# Build settings
markdown: kramdown
